//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSearchResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FSContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FSContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlightSearchResources.FSContent", typeof(FSContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline logo.
        /// </summary>
        public static string AirlineLogoAddressLabel {
            get {
                return ResourceManager.GetString("AirlineLogoAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline name.
        /// </summary>
        public static string AirlineNameLabel {
            get {
                return ResourceManager.GetString("AirlineNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Search Simulator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival airport code:.
        /// </summary>
        public static string ArrAirportCodeDisplay {
            get {
                return ResourceManager.GetString("ArrAirportCodeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival airport code required..
        /// </summary>
        public static string ArrAirportCodeReqError {
            get {
                return ResourceManager.GetString("ArrAirportCodeReqError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival code must be alphanumeric and only 3 characters in length.
        /// </summary>
        public static string ArrAirportCodeReqLengthValidationMsg {
            get {
                return ResourceManager.GetString("ArrAirportCodeReqLengthValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date:.
        /// </summary>
        public static string ArrDateDisplay {
            get {
                return ResourceManager.GetString("ArrDateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date required.
        /// </summary>
        public static string ArrDateReq {
            get {
                return ResourceManager.GetString("ArrDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure airport code:.
        /// </summary>
        public static string DeptAirportCodeDisplay {
            get {
                return ResourceManager.GetString("DeptAirportCodeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure airport code required..
        /// </summary>
        public static string DeptAirportCodeReqError {
            get {
                return ResourceManager.GetString("DeptAirportCodeReqError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure code must be alphanumeric and only 3 characters in length.
        /// </summary>
        public static string DeptAirportCodeReqLengthValidationMsg {
            get {
                return ResourceManager.GetString("DeptAirportCodeReqLengthValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date:.
        /// </summary>
        public static string DeptDateDisplay {
            get {
                return ResourceManager.GetString("DeptDateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date required.
        /// </summary>
        public static string DeptDateReq {
            get {
                return ResourceManager.GetString("DeptDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound flights duration.
        /// </summary>
        public static string InboundFlightsDurationLabel {
            get {
                return ResourceManager.GetString("InboundFlightsDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound flights duration.
        /// </summary>
        public static string OutboundFlightsDurationLabel {
            get {
                return ResourceManager.GetString("OutboundFlightsDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Request.
        /// </summary>
        public static string SearchRequestLabel {
            get {
                return ResourceManager.GetString("SearchRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResultLabel {
            get {
                return ResourceManager.GetString("SearchResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount in USD.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
    }
}
